environment:
  matrix:
    - nodejs_version: "latest"
    - nodejs_version: "stable"
    - nodejs_version: "8"

version: "{build}"
build: off
deploy: off

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

test_script:
  - node --version
  - npm --version
  - npm test
